const mongoose = require("mongoose")

const allPropertyInfo = new mongoose.Schema({
    propertyPurpose:{ type: String },
    propertyType: { type: String },
    subPropertyType: { type: String },
    p_furnitureType: { type: String, default: '' },
    p_isAuthorised: { type: String, default: '' },
    p_masurementUnit: { type: String, default: '' },
    p_totalSize: { type: String, default: '' },
    p_useArea: { type: String, default: '' },
    p_openArea: { type: String, default: '' },
    p_coverArea: { type: String, default: '' },
    p_ownerShipSinces: { type: Date, default: Date.now() },
    p_availableDate: { type: Date, default: Date.now() },
    p_attechment: { type: String, default: '' },
    p_treeCount: { type: String, default: '' },
    p_purchasedFrom: { type: String, default: '' },
    p_maxAsk: { type: String, default: '' },
    p_mainRoadFacing: { type: String, default: '' },
    p_entryGate: { type: String, default: '' },
    p_carParkArea: { type: String, default: '' },
    p_bathrooms: { type: String, default: '' },
    p_pantry: { type: String, default: '' },
    p_cabins: { type: String, default: '' },
    p_workStation: { type: String, default: '' },
    p_conference: { type: String, default: '' },
    p_totalFloors: { type: String, default: '' },
    p_amenities: { type: String, default: '' },
    p_maintainanceFees: { type: String, default: '' },
    p_ownerName: { type: String, default: '' },
    p_ownerDetails: { type: String, default: '' },
    p_ownerContact1: { type: String, default: '' },
    p_ownerContact2: { type: String, default: '' },
    p_ownerStatus: { type: String, default: '' },
    p_nationality: { type: String, default: '' },
    p_state: { type: String, default: '' },
    p_district: { type: String, default: '' },
    p_city: { type: String, default: '' },
    p_landMark: { type: String, default: '' },
    p_area: { type: String, default: '' },
    p_sector: { type: String, default: '' },
    p_flatNo: { type: String, default: '' },
    p_latitude: { type: String, default: '' },
    p_longitude: { type: String, default: '' },
    p_reMarkes: { type: String, default: '' },
    p_boundries: { type: String, default: '' },
    p_balcony: { type: String, default: '' },
    p_kitchn: { type: String, default: '' },
    p_halls: { type: String, default: '' },
    p_toilates: { type: String, default: '' },
    p_rooms: { type: String, default: '' },
})

const model = mongoose.model("allPropertyInfo", allPropertyInfo)
module.exports = model
